packages:
  - apps/**
  - packages/**

allowBuilds:
  '@apollo/protobufjs': false
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  workerd: false

dedupeDirectDeps: true

nodeVersion: 26.8.1

ignoreWorkspaceRootCheck: true
