export const AFFILIATES = 'Affiliates';
export const CHANNELFINDER = 'Channel Finder';
export const BLACKOUTMAP = 'Blackout Map';
export const COVERAGEMAP = 'Coverage Map';
export const COVERAGEMAP506 = 'Coverage Map Courtesy The506.com';
export const SPECIALCOVERAGENOTE = 'See link for full coverage information';

export const imagesForUrls = [
  { link: 'espn3.com', image: 'espn3.jpg' },
  { link: 'espn3&type=live', image: 'espn3.jpg' },
  { link: 'accextra', image: 'accextra.jpg', yearEnd: '2018|201819' },
  { link: 'accextra', image: 'accnx.jpg' },
  { link: 'watchespn.com', image: 'watchespn.jpg', yearEnd: '2016|201617' },
  { link: 'watchespn.com', image: 'watchespn-17.jpg', yearEnd: '2018|201819' },
  { link: 'watchespn.com', image: 'espnapp.jpg' },
  { link: 'ulive', image: 'ulive.jpg' },
  { link: 'cbssports.com', image: 'cbsweb.jpg', yearEnd: '2015|201415' },
  { link: 'cbssports.com', image: 'cbssports-15.jpg', yearEnd: '2020|202021' },
  { link: 'cbssports.com', image: 'cbssports-21.jpg' },
  { link: 'collegesportsdirect.com', image: 'csd.jpg' },
  {
    link: 'collegesportslive.com',
    image: 'cslive.jpg',
    yearEnd: '2017|201617'
  },
  { link: 'collegesportslive.com', image: 'sportslive.jpg' },
  { link: 'slc-now', image: 'slcdn.jpg' },
  { link: 'southland.org/watch', image: 'slcdn.jpg' },
  { link: 'southlanddigitalnetwork', image: 'slcdn.jpg' },
  { link: 'btn2go.com', image: 'btn2go.jpg' },
  { link: 'campusinsiders.com', image: 'ci.jpg' },
  { link: 'patriotleague.tv', image: 'ci.jpg', yearEnd: '2016|201617' },
  { link: 'patriotleague.tv', image: 'pln.jpg' },
  { link: 'facebook.com/StadiumCollegeFootball/', image: 'stadiumfb.jpg' },
  { link: 'facebook.com/StadiumCollegeBasketball', image: 'stadiumfbmbk.jpg' },
  { link: 'network/patriot-league-network', image: 'pln-17.jpg' },
  { link: 'network/wcc-network/', image: 'thewtv.jpg', yearEnd: '2018|201819' },
  { link: 'network/wcc-network/', image: 'wccnetwork.jpg' },
  { link: 'network/mountain-west/', image: 'mwdn.jpg' },
  {
    link: 'themw.com/sports/2017/8/28/broadcast-guide.aspx',
    image: 'mwdn.jpg'
  },
  { link: 'thew.tv', image: 'ci.jpg', yearEnd: '2016|201617' },
  { link: 'watchabc.com', image: 'watchabc.jpg' },
  { link: 'liveextra', image: 'nbcle.jpg', yearEnd: '2015|201516' },
  { link: 'liveextra', image: 'nbcstream.jpg' },
  { link: 'foxsportsgo.com', image: 'fsgo.jpg', yearEnd: '2015|201516' },
  { link: 'foxsportsgo.com', image: 'fsgo-16.jpg' },
  { link: 'secsports.com/watch', image: 'secplus.jpg' },
  { link: 'secplus', image: 'secplus.jpg' },
  { link: 'thew.tv', image: 'thewtv.jpg', yearEnd: '2018|201819' },
  { link: 'thew.tv', image: 'wccnetwork.jpg' },
  { link: 'wccsports.com', image: 'thewtv.jpg', yearEnd: '2018|201819' },
  { link: 'wccsports.com', image: 'wccnetwork.jpg' },
  { link: 'beinsportsconnect.tv', image: 'beinconnect.jpg' },
  { link: 'go90.com/shows/3Qh33oOSYJo', image: 'stadiumgo90.jpg' },
  { link: 'ESPN_PLUS&type=live', image: 'espn_plus.jpg' },
  { link: 'facebook.com/LiveCUSA', image: 'cbssn-fb.jpg' },
  { link: 'facebook.com/CBSSports', image: 'cbssn-fb.jpg' },
  { link: 'flofootball.com', image: 'flofootball.jpg', yearEnd: '2018|201819' },
  { link: 'flohoops.com', image: 'flohoops.jpg', yearEnd: '2018|201819' },
  {
    link: 'flofootball.com',
    image: 'flosports-19.jpg',
    yearEnd: '2020|202021'
  },
  { link: 'flohoops.com', image: 'flosports-19.jpg', yearEnd: '2020|202021' },
  {
    link: 'flofootball.com',
    image: 'flofootball-21.jpg',
    yearEnd: '2023|202324'
  },
  { link: 'flohoops.com', image: 'flohoops-21.jpg', yearEnd: '2023|202324' },
  { link: 'flofootball.com', image: 'flocollege.jpg' },
  { link: 'flohoops.com', image: 'flocollege.jpg' },
  { link: 'twitch.tv/elevensportsnext', image: 'elevennext.jpg' },
  { link: 'pluto.tv', image: 'plutotv.jpg' },
  { link: 'necfrontrow', image: 'necfrontrow.jpg' },
  { link: 'ovcdigitalnetwork', image: 'ovcdn.jpg' },
  { link: 'caa.tv', image: 'caatv.jpg' },
  { link: 'nbcsports.com/boston', image: 'nbcstream.jpg' },
  { link: 'nbcsports.com/live', image: 'nbcstream.jpg' },
  { link: 'nbcsports.com/watch', image: 'nbcstream.jpg' },
  { link: 'btnplus', image: 'btnplus.jpg', yearEnd: '2018|201819' },
  { link: 'btnplus', image: 'btnplus2.jpg', yearEnd: '2019|201920' },
  { link: 'btnplus', image: 'btnplus-20.jpg' },
  { link: 'cusa.tv', image: 'cusatv.jpg' },
  { link: 'bigwest.tv', image: 'bigwest.jpg' },
  { link: 'bigwest.sidearm', image: 'bigwest.jpg' },
  { link: 'wacdigitalnetwork', image: 'wacdn.jpg' },
  { link: 'foxsports.com/live', image: 'foxsports.jpg' },
  { link: 'barstoolsports.com', image: 'barstool.jpg' },
  { link: 'peacocktv.com', image: 'peacock.jpg' },
  { link: 'paramountplus.com', image: 'paramountplus.jpg' },
  { link: 'themw.com/watch', image: 'mwdn.jpg' },
  { link: 'midcosportsplus.com', image: 'summitnet.jpg' },
  { link: 'max.com', image: 'max.jpg' },
  { link: 'youtube.com', image: 'youtube.jpg' }
];
