export const conferenceData = [
  {
    id: 'acc',
    data: '<p>The ACC has a contract with ABC/ESPN for all of its football television rights. ESPN\'s broadband service, ESPN3.com, can also access games that are not slated for telecast.  This contract begins with the 2011-12 athletic year and ends with the 2026-27 athletic year.</p><p>Raycom is the syndication partner of the ACC and they sublicense their content from ESPN.  Raycom will manage both over-the-air and regional cable syndication packages. The regional cable package appears to have been sublicensed to FOX Sports Media Group for airing on some FSN affiliates, NESN and Comcast SportsNet Mid-Atlantic.  Raycom&#39;s package of over-the air games are branded as the ACC Network. The ACC Network over-the-air telecasts will kickoff at 12:30pm ET. ESPN is also able to sublicenese games to other national carriers.</p><p>It does not appear that there are any limits/minimums in terms of number of games over a season for the ACC with their national TV contracts. The ACC is guaranteed a game on Labor Day by ESPN.</p><p>To cover the additions of Syracuse and Pittsburgh to the conference, the ACC signed an extension with ESPN for more money per school, adding years to the deal that started with the 2011-12 athletic year. Items relevant to football include that the ACC will have up to three Friday night football games per season, one of those three to be played on Black Friday in the afternoon or evening. Specifically, Boston College and Syracuse will each host one Friday night game per year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/07/espn-and-acc-reach-exclusive-12-year-agreement/" target="_blank">ESPN PressRoom (2010)</a>, <a href="https://espnpressroom.com/us/press-releases/2012/05/espn-and-acc-extend-exclusive-multi-platform-agreement-through-2026-27/" target="_blank">ESPN PressRoom (2012)</a></p>'
  },
  {
    id: 'b1g',
    data: '<p>The Big Ten has a contract with ESPN for 41 games and a regional TV contract with the Big Ten Network (BTN), a FOX Sports Media Group &amp; Big Ten joint venture. There were previously stipulations on the maximum number of games on ABC (17) and ESPN cable platforms (25), but those numbers have went away. Now the ESPN platforms have a total of 41 games that they can spread over ABC, ESPN, ESPN2 and ESPNU.</p><p>For selection order, ABC has the first selection of games every week. Most weeks ESPN/ESPN2 will have the next set of game choices, followed by BTN. BTN will be able to leapfrog ESPN and/or ESPN2 on select weekends.</p>Starting with 2011, ABC has given up exclusivity in the 3:30pm telecast window. BTN will now be allowed to schedule games during the 3:30pm time slot if it desires.</p><p>FOX Sports, under a separate contract, has the rights to the conference championship game. These rights started in 2011 and will end after the 2016 championship game.</p><p>Source: <a href="http://www.bigten.org/genrel/062106aad.html" target="_blank">Big Ten regular season</a>, <a href="http://www.bigten.org/sports/m-footbl/spec-rel/111710aaa.html" target="_blank">Big Ten championship game</a></p>'
  },
  {
    id: 'b12',
    data: '<p>The Big 12 a pair of contracts with ESPN and FOX Sports Media Group. Both contracts expire after the 2024-25 athletic year.</p><p>The ESPN deal allows for 19 games per year from 2012-2015, then 23 games starting in 2016. Games can air on ABC, ESPN, ESPN2, ESPNU and Longhorn Network (Texas games only). FOX\'s deal is for up to 40 games per year to place games on FOX, F/X, FSN and FOX College Sports. A minimum of six of FSMG\'s games must appear on FOX. Overall, a minimum of 25 games must air on ABC, ESPN, F/X or FOX.</p><p>Individual institutions will retain the rights to at least one game not aired by ABC or FSMG, allowing those institutions to explore other avenues to televising those games. Institutions can elect to return their institutional game to FOX for their package to televise.</p><p>Regarding Longhorn Network, one Texas game per year airing on the network counts as an institutional game, like all other Big 12 schools. Any subsequent Texas games airing on Longhorn Network will count towards the ESPN contract.</p><p>As part of the FSMG contract, up to three games can move to Thursdays and the network has the ability to place games on the Friday after Thanksgiving and Sunday of Labor Day weekend.</p><p>Source: <a href="http://www.big12sports.com/ViewArticle.dbml?ATCLID=205680799" target="_blank">Big 12</a>'
  },
  {
    id: 'beast',
    data: '<p>The Big East has contracts with ABC for network TV, ESPN Networks for national cable and ESPN Regional Television for regional syndication. In order of preference, ABC gets first choice, followed by ESPN Networks, then ESPN Regional TV (aka Big East Network). ESPN&#39;s broadband service, ESPN3, is also allowed to select games not chosen for television. This contract expires after the 2013 football season.</p><p>ABC/ESPN will guarantee the conference:</p><ul><li>Minimum of 17 games on ABC/ESPN/ESPN2</li><li>Of those 17, up to four will appear on ESPN Thursday nights, one for ESPN Saturday night, up to two on Sunday nights</li><li>An additional minimum of five games on ESPNU.</li></ul><p>Source: <a href="http://www.bigeast.com/genrel/082906aab.html" target="_blank">Big East</a></p>'
  },
  {
    id: 'cusa',
    data: '<p>Conference USA has three rights holders: ESPN, FOX Sports Media Group and CBS Sports Network.</p><p>FOX Sports Media Group will air at least 20 football games per season and air the conference\'s championship game.  Games can air on FOX Broadcasting, FSN or F/X with most games expected to air on FSN.  It is unknown how many games CBS Sports Network will air, but their previous contract was for 24 games per season and allowed for games to be sublicensed to Comcast/Charter Sports Southeast (CSS).</p><p>What is known is that FOX will be able to select the top ten games from the conference. CBS Sports Network will then select the next ten, and FOX will then come back and select another ten games.</p><p>ESPN, to settle a lawsuit between the conference and the network, has the rights to the conference championship game.</p><p>All of C-USA\'s contracts expire after the 2015-16 athletic year.</p><p>Source: <a href="http://www.conferenceusa.com/genrel/010511aac.html" target="_blank">C-USA on FOX</a>, <a href="http://www.conferenceusa.com/genrel/072210aaa.html" target="_blank">C-USA on CBSSN</a>, <a href="http://espn.go.com/college-football/story/_/id/6866698/conference-usa-espn-settle-lawsuit-contract" target="_blank">C-USA with ESPN</a>, <a href="http://www.sportsbusinessdaily.com/Journal/Issues/2011/02/28/Media/Conf-USA.aspx" target="_blank">Sports Business Journal</a></p>'
  },
  {
    id: 'mac',
    data: '<p>The MAC has a national cable &amp; regional syndication contract with ESPN Networks and a regional television package with SportsTime Ohio.</p><p>At least six regular season games will air on ESPN or ESPN2, plus a minimum of five games on ESPNU.  For regional television, ESPN Regional TV will air games over six weekends on local stations and SportsTime Ohio will carry a minimum of three games.</p><p>Source: <a href="http://www.niuhuskies.com/genrel/012809aab.html" target="_blank">Northern Illinois</a></p>'
  },
  {
    id: 'mw',
    data: '<p>The MWC has a national cable contract with CBS Sports Network. As membership is changing in 2012 and again in 2013, CBS Sports Network has made deals to sublicense games to NBC Sports Network and ESPN.</p><p>Source: <a href="http://www.cbscorporation.com/news-article.php?id=405" target="_blank">CBS</a>, <a href="http://www.themw.com/news/sports-m-footbl-spec-rel-050312aae" target="_blank">MWC</a></p>'
  },
  {
    id: 'p12',
    data: '<p>The Pac-12 has a pair of rightsholders: ESPN and FOX Sports Media Group. Contracts with both entities start with the 2012-13 athletic year and end after the 2023-24 athletic year.</p><u>ESPN Rights Notes</u><ul><li>Two games on ABC</li><li>Twenty games on ESPN Networks (ESPN, ESPN2 &amp; ESPNU)</li><li>Of the twenty games on ESPN Networks, up to four games on Thursday nights &amp; up to four games on Friday night.</li><li>Up to four of the twenty games can air on ESPNU</li><li>Most ESPN/ESPN2 Saturday games will air at 10pm ET</li></ul><u>FSMG Rights Notes</u><ul><li>A minimum of eight games on FOX</li><li>A maximum of fourteen games on F/X</li><li>At least four games on FOX will air in primetime.</li></ul><p>FOX and ESPN will alternate airing the Pac-12 Championship Game.  In even-numbered seasons, FOX will air the game.  ESPN will air it in odd-numbered years.</p><p>The conference has also created the Pac-12 Networks, a mix of six regional networks and a national networks, to air all other games.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2011/05/espn-and-pac-12-reach-wide-ranging-12-year-agreement/" target="_target">ESPN PressRoom, <a href="https://www.facebook.com/notes/fox-sports/fox-sports-media-group-secures-pac-12-multi-platform-media-rights/10150232924355700" target="_target">Facebook for FOX</a></p>'
  },
  {
    id: 'sec',
    data: '<p>The SEC has a network TV contract with CBS, a national cable deal with ESPN Networks and a regional syndication contract with ESPN Regional Television.</p><p>CBS has the rights to 12-15 regular season games and the conference championship. Up to two of those games can be non-conference games. CBS will always have the top choice of SEC games on a weekly basis.  When CBS does a doubleheader that includes a primetime game, CBS can choose the top two games on a given weekend.  When they do a doubleheader that includes a 12pm game, it must allow ESPN to reserve two games before selecting their next game.</p><p>ESPN Networks has the rights to remaining SEC home games, primarily prime time telecasts. ESPN Regional Television\'s primary syndicated game (aka SEC Network) will be in the early afternoon (12:21pm EST). ESPN has also reached syndication deals with CSS and the southeast-based FOX Sports regional networks for games.  One game per team per season can be shown on a PPV or local TV basis.</p><p>Due to the acceptance of Texas A&amp;M and Missouri as new members, plus negotiations between CBS and ESPN to allow the primetime telecast of LSU-Alabama in 2011, there may be alterations signed to the deals.</p><p>Source: <a href="http://www.gatorzone.com/story.php?id=14419" target="_blank">Florida</a>, <a href="http://www.sportsbusinessdaily.com/Journal/Issues/2008/08/20080818/This-Weeks-News/CBS-To-Pay-SEC-Average-Of-$55-Million-Annually.aspx" target="_blank">Sports Business Journal</a></p>'
  },
  {
    id: 'sbc',
    data: '<p>The Sun Belt has an eight year contract with ESPN, starting with the 2012-13 athletic year and ending with the 2019-20 athletic year. A minimum of two football games will air on ESPN or ESPN2. ESPNU will air a minimum of five games on Thursdays or Fridays. ESPN Regional Television can also select up to five games. ESPN3 can also select games throughout the season.</p><p>COX Sports and CSS also manage the Sun Belt\'s primary regional package, known as the Sun Belt Network.</p><a href="https://espnpressroom.com/us/weekly-updates/2011/midweek_20110908/#L" target="_blank">ESPN PressRoom</a>, <a href="http://coxsportstv.com/featured-teams/other-sports/news/extension-of-sun-belt-network-partnership-announced" target="_blank">CST</a></p>'
  },
  {
    id: 'wac',
    data: 'The WAC has a contract with ESPN through the 2016-17 athletic year. The contents of the deal have been modified since the original signing due to membership changes and it is unclear how many games will air on ESPN Networks, ESPN Regional Television or ESPN3.</p><p>Source: <a href="http://www.wacsports.com/ViewArticle.dbml?DB_OEM_ID=10100&ATCLID=1574229" target="_blank">WAC</a></p>'
  },
  {
    id: 'Army',
    data: 'Army has a contract for home game telecasts with CBS Sports Network, with the exception of the Army-Navy game which is handled separately. The contract is for five years, ending after the 2014 season.</p><p>Source: <a href="http://www.goarmysports.com/sports/m-footbl/spec-rel/072209aaa.html" target="_blank">Army (CBS)</a>, <a href="http://www.goarmysports.com/sports/m-footbl/spec-rel/102308aad.html" target="_blank">Army-Navy</a></p>'
  },
  {
    id: 'BYU',
    data: '<p>BYU has an eight year deal with ABC/ESPN, ending after the completion of the 2018 season.  At least three home games will air on ABC, ESPN or ESPN2.  A minimum of one game will air on ESPNU and BYUtv, the broadcasting arm of BYU, must air at least one game per season.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/09/espn-and-byu-reach-agreement-for-football-rights-beginning-in-2011/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'Navy',
    data: '<p>Navy contracts with CBS Sports Network for their home games, except for the Army-Navy game and when Navy is the home team vs. Notre Dame (CBS has that game).  The contract covers through the 2017 football season with an option to air Navy\'s hosted game vs. Notre Dame in 2018 on CBS.</p><p>Source: <a href="http://www.navysports.com/sports/m-footbl/spec-rel/091808aab.html" target="_blank">Navy</a></p>'
  },
  {
    id: 'Notre Dame',
    data: '<p>Rights to Notre Dame home games, including neutral site "home" games, are held by NBC.  The contract requires for seven "home" games per year, including neutral site games.  The contract does allow for games to air on cable stations owned by NBC, such as NBC Sports Network.  The contract expires after the 2015 season.</p><p>Source: <a href="http://news.nd.edu/news/9528-notre-dame-nbc-extend-football-contract-through-2015/" target="_blank">Notre Dame</a></p>'
  }
];
