export const conferenceData = [
  {
    id: 'acc',
    data: '<p>The ACC has a contract with ABC/ESPN for all of its football television rights. ESPN\'s broadband service, ESPN3.com, can also access games that are not slated for telecast.  This contract begins with the 2011-12 athletic year and ends with the 2026-27 athletic year.</p><p>Raycom is the syndication partner of the ACC and they sublicense their content from ESPN.  Raycom will manage both over-the-air and regional cable syndication packages. The regional cable package appears to have been sublicensed to FOX Sports Media Group for airing on some FSN affiliates, NESN and Comcast SportsNet Mid-Atlantic.  Raycom&#39;s package of over-the air games are branded as the ACC Network. The ACC Network over-the-air telecasts will kickoff at 12:30pm ET. ESPN is also able to sublicenese games to other national carriers.</p><p>It does not appear that there are any limits/minimums in terms of number of games over a season for the ACC with their national TV contracts. The ACC is guaranteed a game on Labor Day by ESPN.</p><p>To cover the additions of Syracuse and Pittsburgh to the conference, the ACC signed an extension with ESPN for more money per school, adding years to the deal that started with the 2011-12 athletic year. Items relevant to football include that the ACC will have up to three Friday night football games per season, one of those three to be played on Black Friday in the afternoon or evening. Specifically, Boston College and Syracuse will each host one Friday night game per year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/07/espn-and-acc-reach-exclusive-12-year-agreement/" target="_blank">ESPN PressRoom (2010)</a>, <a href="https://espnpressroom.com/us/press-releases/2012/05/espn-and-acc-extend-exclusive-multi-platform-agreement-through-2026-27/" target="_blank">ESPN PressRoom (2012)</a></p>'
  },
  {
    id: 'aac',
    data: '<p>The American Athletic Conference has a contract with ESPN Networks for all of their football television rights.  ABC/ESPN will guarantee the conference a minimum of 28 games to air on ABC, ESPN, ESPN2 and ESPNU with a minimum of three of the 28 games on ABC.  Games may also appear on ESPNEWS and ESPN3.</p><p>Navy, who is entering the conference in 2015, will continue to have the rights to their home games retained by CBS Sports Network under an existing agreement, except for the Army-Navy game and when Navy is the home team vs. Notre Dame (CBS has that game).  The Navy telvision contract covers through the 2017 football season with an option to air Navy\'s hosted game vs. Notre Dame in 2018 on CBS.  Navy&#39;s American Athletic Conference road games will be part of the conference&#39;s rights package with ESPN.</p><p>The contract with ESPN, along with ESPN\'s sublicense agreement with CBS Sports Network, end after the 2019-2020 athletic year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2013/03/espn-and-current-big-east-conference-agree-to-multiyear-rights-agreement/" target="_blank">ESPN PressRoom</a>, <a href="http://www.cbspressexpress.com/cbs-sports-network/releases/view?id=36355" target="_blank">CBS Press Express</a>, <a href="http://theamerican.org/documents/2016/7/7//fb_preview_2016_min.pdf" target="_blank">American (ABC minimum, page 4)</a></p>'
  },
  {
    id: 'b1g',
    data: '<p>The Big Ten has a contract with ESPN and a secondary TV contract with the Big Ten Network (BTN), a FOX Sports Media Group &amp; Big Ten joint venture. ESPN\'s games can spread over ABC, ESPN, ESPN2, ESPNU and ESPNEWS.  With the addition of Maryland and Rutgers in 2014, the number of games available to ESPN will increase from 41 to an undisclosed number.</p><p>For selection order, ABC has the first selection of games every week. Most weeks ESPN/ESPN2 will have the next set of game choices, followed by BTN. BTN will be able to leapfrog ESPN and/or ESPN2 on select weekends.</p><p>FOX Sports, under a separate contract, has the rights to the conference championship game. These rights started in 2011 and will end after the 2016 championship game.</p><p>Source: <a href="http://www.bigten.org/genrel/062106aad.html" target="_blank">Big Ten regular season</a>, <a href="http://www.bigten.org/sports/m-footbl/spec-rel/111710aaa.html" target="_blank">Big Ten championship game</a></p>'
  },
  {
    id: 'b12',
    data: '<p>The Big 12 a pair of contracts with ESPN and FOX Sports Media Group. Both contracts expire after the 2024-25 athletic year.</p><p>The ESPN deal allows for 19 games per year from 2012-2015, then 23 games starting in 2016. Games can air on ABC, ESPN, ESPN2, ESPNU and Longhorn Network (see note below re: LHN). FOX\'s deal is for up to 40 games per year to place games on FOX, FOX Sports 1, FSN and FOX College Sports. A minimum of six of FSMG\'s games must appear on FOX with another six on FOX Sports 1. Overall, a minimum of 25 games must air on ABC, ESPN, FOX and FOX Sports 1.</p><p>Individual institutions will retain the rights to at least one game not aired by ABC or FSMG, allowing those institutions to explore other avenues to televising those games. Institutions can elect to return their institutional game to FOX for their package to televise.</p><p>Regarding Longhorn Network, one Texas game per year airing on the network counts as an institutional game, like all other Big 12 schools. Any subsequent Texas games airing on Longhorn Network will count towards the ESPN contract.</p><p>Source: <a href="http://www.big12sports.com/ViewArticle.dbml?ATCLID=205680799" target="_blank">Big 12</a>'
  },
  {
    id: 'cusa',
    data: '<p>Conference USA has four rights holders: FOX Sports Media Group, CBS Sports Network, ESPN and Sinclair Broadcast Group\'s American Sports Network.</p><p>FOX Sports Media Group will air at least 30 football games per season.  Games can air on FOX Broadcasting, FOX Sports 1, FSN and FOX College Sports.  In 2013, ten games were guaranteed to air on FOX Sports 1.  It is unknown how many games CBS Sports Network will air, but their previous contract was for 24 games per season.</p><p>FOX will be able to select the top ten games from the conference. CBS Sports Network will then select the next ten, and FOX will then come back and select another ten games.</p><p>ESPN, to settle a lawsuit between the conference and the network, has the rights to the conference championship game.</p><p>New for 2014, Sinclair Broadcast Group established a syndication arm called the American Sports Network.  The games picked up by this package will air on Sinclair\'s CW and My Network TV affiliates and digital subchannels.  Markets not served by a Sinclair-owned and/or operated TV station are likely to have a local station pick up games in the package.</p><p>After all TV contracts have been satisfied, additional games can be picked up for regional or national airings.  FOX College Sports has picked up games after the main FOX package has been set.</p><p>All of C-USA&#39;s contracts expire after the 2015-16 athletic year.</p><p>Source: <a href="http://www.conferenceusa.com/genrel/010511aac.html" target="_blank">C-USA on FOX</a>, <a href="http://www.conferenceusa.com/genrel/072210aaa.html" target="_blank">C-USA on CBSSN</a>, <a href="http://www.conferenceusa.com/genrel/071714aaa.html" target="_blank">C-USA on ASN</a>, <a href="http://espn.go.com/college-football/story/_/id/6866698/conference-usa-espn-settle-lawsuit-contract" target="_blank">C-USA with ESPN</a>, <a href="http://www.sportsbusinessdaily.com/Journal/Issues/2011/02/28/Media/Conf-USA.aspx" target="_blank">Sports Business Journal</a></p>'
  },
  {
    id: 'mac',
    data: '<p>The MAC has a national cable contract with ESPN Networks.  The contract runs through the 2026-27 athletic year.  ESPN\'s contract includes the ability to sublicense games and guaranteed coverage for all MAC games.</p><p>The previous contract allowed for at least six regular season games will air on ESPN or ESPN2, plus a minimum of five games on ESPNU.  ESPN3 will be used for any game not distributed on some form of national or regional television.  ESPN is working with the schools to self-produce ESPN3 content, providing them with production equipment.</p><p>Starting with the 2015 season, Sinclair\'s American Sports Network, CBS Sports Network and Buckeye Cable will sublicense MAC content from ESPN.  For 2015, CBSSN will sublicense six football games (two Thursday night games, one Black Friday game and three Saturday games). Future seasons will allow for sublicensing of 12 football games.  This agreement ends after the 2018-19 athletic year. American Sports Network will sublicense ten football games for the 2015-16 and 2016-17 athletic years from ESPN.  Buckeye Cable will show at least three football games per season and work to clear the games on other cable systems in the MAC footprint.</P><p>Source: <a href="http://www.niuhuskies.com/genrel/012809aab.html" target="_blank">Northern Illinois</a>, <a href="http://mac-sports.com/news/2014/8/19/GEN_0819145904.aspx" target="_blank">MAC (contract extension)</a>, <a href="http://mac-sports.com/news/2015/6/2/FB_0602151727.aspx" target="_blank">MAC (CBSSN sublicense)</a>, <a href="http://mac-sports.com/news/2015/9/3/FB_0903152549.aspx" target="_blank">MAC (ASN sublicense)</a>, <a href="http://mac-sports.com/news/2015/9/28/FB_0928150516.aspx" target="_blank">MAC (Buckeye Cable)</a></p>'
  },
  {
    id: 'mw',
    data: '<p>The MWC has a pair of national cable contracts with CBS Sports Network and ESPN.</p><p>CBS is considered to be the "primary" TV partner.  CBS will be able to choose the top eight football games each year, then alternate with ESPN for the rest of their picks. This package is for up to 22 games. CBS\'s contract ran through the 2015-16 athletic year, with CBS having an option to extend the deal through the 2019-20 athletic year.  Per the conference, the option has been picked up.</p><p>ESPN\'s package also runs through the 2019-20 athletic year and includes the rights to Boise St. home games. At least three Boise St. football games will air on ABC, ESPN, ESPN2.  ESPN can choose the platform of its choice for all other Boise St. home games. No more than three Boise St. home games can be moved to a weeknight. ESPN will have up to 22 football games including the Boise St. home games. ESPN does have the ability to trade one Boise St. home game per year to CBS in exchange for a Boise St. road games at a MWC opponent.</p><p>The contract for the conference&#39;s championship game is with ESPN starting with the 2015 game & running through the 2019 game.  The game will air on ESPN or ESPN2. CBS declined an option to carry the 2015 game.</p><p>The official regional partner for the MWC is ROOT Sports Rocky Mountain, who will produce around 10 football games annually.  Campus Insiders also works with the conference to produce games that will be streamed through the Moutain West Digital Network.</p><p>ESPN and CBS select up to two more games each once ROOT Sports and Campus Insiders select games for their packages, meaning ESPN and CBS could show up to 24 games.</p><p>Hawai\'i does not receive money from the MW TV contract unless all other Mountain West schools receive $2.3 million from the conference TV contracts.  Instead, they receive revenue from a contract with Oceanic Cable in Hawai\'i.  The contract requires at least seven games per year to be provided to the cable provider.</p><p>Source: <a href="http://www.cbssports.com/collegefootball/writer/dennis-dodd/21436698/mountain-west-restructures-deal-with-cbs" target="_blank">CBS</a>, <a href="https://espnpressroom.com/us/press-releases/2013/03/espn-and-mountain-west-conference-announce-multiyear-rights-agreement/" target="_blank">ESPN</a>, <a href="http://www.themw.com/news/espn_mwfb_champ" target="_blank">MWC for football championship</a>, <a href="http://www.themw.com/news/genrel-061013aaa" target="_blank">Campus Insiders</a>, <a href="https://broncosports.com/news/2013/3/26/Boise_State_and_Mountain_West_Announce_TV_Deal_with_ESPN.aspx" target="_blank">Boise St.</a>, <a href="https://broncosports.com/news/2013/5/15/Mountain_West_ROOT_SPORTS_Announce_Partnership.aspx" target="_blank">Boise St. for ROOT Sports</a></p>'
  },
  {
    id: 'p12',
    data: '<p>The Pac-12 has a pair of rightsholders: ESPN and FOX Sports Media Group. Contracts with both entities start with the 2012-13 athletic year and end after the 2023-24 athletic year.</p><u>ESPN Rights Notes</u><ul><li>At least two games on ABC, with one game required to air in primetime on the east coast</li><li>Up to twenty games on ESPN Networks (ESPN, ESPN2 &amp; ESPNU)</li><li>Of the twenty games on ESPN Networks, up to four games on Thursday nights &amp; up to four games on Friday night.</li><li>Up to four of the twenty games can air on ESPNU</li><li>Most ESPN/ESPN2 Saturday games will air at 10pm or 10:30pm ET</li></ul><u>FSMG Rights Notes</u><ul><li>A minimum of eight games on FOX</li><li>A maximum of fourteen games on FOX Sports 1</li><li>At least four games on FOX will air in primetime.</li></ul><p>Overall, the conference works with both ESPN and FOX to place at least four games on Thursdays and another four games on Fridays, including the day after Thanksgiving.  FOX and ESPN will alternate airing the Pac-12 Championship Game.  In even-numbered seasons, FOX will air the game.  ESPN has the rights in odd-numbered years.</p><p>The conference has also created the Pac-12 Networks, a mix of six regional networks and a national networks, to air all other games.</p><p>A school may not appear more than nine times combined in the ESPN and FOX packages.  This is to allow the Pac-12 Networks to air at least one game from every school, assuming a school plays at least one home non-conference game.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2011/05/espn-and-pac-12-reach-wide-ranging-12-year-agreement/" target="_target">ESPN PressRoom, <a href="https://www.facebook.com/notes/fox-sports/fox-sports-media-group-secures-pac-12-multi-platform-media-rights/10150232924355700" target="_target">Facebook for FOX</a></p>'
  },
  {
    id: 'sec',
    data: '<p>The SEC has a network TV contract with CBS, a national cable deal with ESPN Networks and a new conference branded network called the SEC Network, which is completely owned by ESPN.</p><p>CBS has the rights to 12-15 regular season games and the conference championship. Up to two of those games can be non-conference games. CBS will always have the top choice of SEC games on a weekly basis.  When CBS does a doubleheader that includes a primetime game, CBS can choose the top two games on a given weekend.  When they do a doubleheader that includes a 12pm game, it must allow ESPN to reservetwo games before selecting their next game.  Also, a school may not appear on CBS more than five times during the season, with some exceptions allowing for a sixth appearance.  The SEC Championship Game is never part of the appearance count.</p><p>ESPN Networks has the rights to remaining SEC home games, primarily prime time telecasts.  A content board will be established to determine which games will air on ESPN and the SEC Network.  The plan is to air a tripleheader of games every week.  There will overflow or alternate feeds of the network to allow for multiple games to air in a single telecast window.</p><p>For 2015, CBS has sublicensed two games from ESPN.  They are the Louisville vs. Auburn game on 9/5 and the Georgia at Vanderbilt game on 9/12.  Per SEC media contact Chuck Dunlap, these two games do not count towards any CBS appearance counts.</p><p>Source: <a href="http://www.gatorzone.com/story.php?id=14419" target="_blank">Florida</a>, <a href="https://www.cbssports.com/college-football/news/sec-cbs-rework-long-term-contract/" target="_blank">CBS Sports</a>, <a href="https://espnpressroom.com/us/press-releases/2013/05/the-southeastern-conference-and-espn-announce-new-tv-network-and-digital-platform/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'sbc',
    data: '<p>The Sun Belt has an eight year contract with ESPN, starting with the 2012-13 athletic year and ending with the 2019-20 athletic year. A minimum of two football games will air on ESPN or ESPN2. ESPNU will air a minimum of five games on Thursdays or Fridays. ESPN Regional Television can also select up to five games. ESPN3 can also select games throughout the season.</p><p>Source: <a href="https://espnpressroom.com/us/weekly-updates/2011/midweek_20110908/#L" target="_blank">ESPN PressRoom</a>, <a href="http://www.sunbeltsports.org/news/2014/7/16/BB_0716144040.aspx" target="_blank">Sun Belt on ESPN3</a></p>'
  },
  {
    id: 'Army',
    data: '<p>Army has a contract for home game telecasts with CBS Sports Network, with the exception of the Army-Navy game which is handled separately. A new contract has been reached between Army and CBSSN, starting in 2015 and covering five seasons, ending after the 2019 season.</p><p>Source: <a href="http://onlyfans.cstv.com/schools/army/sports/m-footbl/spec-rel/011515aaa.html" target="_blank">Army (CBS)</a>, <a href="http://www.goarmysports.com/sports/m-footbl/spec-rel/102308aad.html" target="_blank">Army-Navy</a></p>Army has a contract for home game telecasts with CBS Sports Network, with the exception of the Army-Navy game which is handled separately. The contract is for five years, ending after the 2014 season.</p><p>Source: <a href="http://www.goarmysports.com/sports/m-footbl/spec-rel/072209aaa.html" target="_blank">Army (CBS)</a>, <a href="http://www.goarmysports.com/sports/m-footbl/spec-rel/102308aad.html" target="_blank">Army-Navy</a></p>'
  },
  {
    id: 'BYU',
    data: '<p>BYU has an eight year deal with ABC/ESPN, ending after the completion of the 2018 season.  At least three home games will air on ABC, ESPN or ESPN2.  A minimum of one game will air on ESPNU and BYUtv, the broadcasting arm of BYU, must air at least one game per season.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/09/espn-and-byu-reach-agreement-for-football-rights-beginning-in-2011/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'Notre Dame',
    data: '<p>Rights to Notre Dame home games, including neutral site "home" games, are held by NBC.  The contract requires for seven "home" games per year, including neutral site games.  A new, extended contract allows for games to air on cable stations owned by NBC, such as NBC Sports Network.  The extended contract expires after the 2025 season.</p><p>Source: <a href="http://news.nd.edu/news/9528-notre-dame-nbc-extend-football-contract-through-2015/" target="_blank">Notre Dame</a></p>'
  }
];
