import type { ConferenceData } from './conferenceData';

export const conferenceData: ConferenceData[] = [
  {
    id: 'acc',
    data: '<p>The ACC has a contract with ABC/ESPN for all of its football television rights.  This contract begins with the 2011-12 athletic year and ends with the 2036-37 athletic year.</p><p>Raycom is the syndication partner of the ACC and they sublicense their content from ESPN.  Raycom will manage both over-the-air and regional cable syndication packages. The regional cable package appears to have been sublicensed from Raycom to FOX Sports Media Group for airing on some FSN affiliates, NESN and Comcast SportsNet Mid-Atlantic.  Raycom&#39;s package of over-the air games are branded as the ACC Network. The ACC Network over-the-air telecasts will kickoff at 12:30pm ET.  ESPN is also able to sublicenese games to other national carriers.  In 2019, ESPN will launch their own ACC Network, with the 2018 season being the last for Raycom\'s sublicense of ACC games.</p><p>It does not appear that there are any limits/minimums in terms of number of games over a season for the ACC with their national TV contracts. The ACC is guaranteed a game on Labor Day by ESPN.</p><p>Starting with the 2016 season, the ACC will have its own digital platform called ACC Network Plus.  The platform will carry all Raycom Sports games outside of the ACC\'s footprint along with games previously aired exclusively on ESPN3.  This platform will precede a linear television channel which is expected to be available to television providers starting with the 2019-20 athletic year.  At that time, all games sublicensed to Raycom, including regional cable games passed through to FOX Sports, will revert back to ESPN\'s control. </p><p>To cover the additions of Syracuse and Pittsburgh to the conference, the ACC signed an extension with ESPN for more money per school, adding years to the deal that started with the 2011-12 athletic year. Items relevant to football include that the ACC will have up to three Friday night football games per season, one of those three to be played on Black Friday in the afternoon or evening. Specifically, Boston College and Syracuse will each host one Friday night game per year.<p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/07/espn-and-acc-reach-exclusive-12-year-agreement/" target="_blank">ESPN PressRoom (2010)</a>, <a href="https://espnpressroom.com/us/press-releases/2012/05/espn-and-acc-extend-exclusive-multi-platform-agreement-through-2026-27/" target="_blank">ESPN PressRoom (2012)</a>, <a href="https://espnpressroom.com/us/press-releases/2016/07/acc-network-set-launch-2019/">ESPN PressRoom (2016)</a></p>'
  },
  {
    id: 'aac',
    data: '<p>The American Athletic Conference has a contract with ESPN Networks for all of their football television rights.  ABC/ESPN will guarantee the conference a minimum of 28 games to air on ABC, ESPN, ESPN2 and ESPNU with a minimum of three of the 28 games on ABC.  Games may also appear on ESPNEWS and ESPN3.</p><p>ESPN has elected to sublicense 13-15 games per year to CBS Sports Network.  Navy\'s home games will air on CBS Sports Network in 2018 & 2019 as well under a new agreement.  Starting in 2020, the conference\'s primary rightsholder will have access to one Navy home game per season plus the "home" game vs. Notre Dame every other year.  The rest will air on CBS Sports Network through 2027.</p><p>The contract with ESPN, along with ESPN\'s sublicense agreement with CBS Sports Network, end after the 2019-2020 athletic year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2013/03/espn-and-current-big-east-conference-agree-to-multiyear-rights-agreement/" target="_blank">ESPN PressRoom</a>, <a href="http://www.cbspressexpress.com/cbs-sports-network/releases/view?id=36355" target="_blank">CBS Press Express</a>, <a href="http://theamerican.org/documents/2016/7/7//fb_preview_2016_min.pdf" target="_blank">American (ABC minimum, page 4)</a>, <a href="http://www.theamerican.org/news/2018/5/9/football-cbs-sports-american-athletic-conference-and-navy-extend-partnership-through-2027-season.aspx" target="_blank">American & Navy</a></p>'
  },
  {
    id: 'b1g',
    data: '<p>The Big Ten has primary television contracts with ESPN and FOX Sports and a secondary TV contract with the Big Ten Network (BTN), a FOX Sports Media Group &amp; Big Ten joint venture.</p><u>ESPN Rights Notes</u><ul><li>27 total games.</li><li>All intraconference games must air on ABC, ESPN or ESPN2.</li><li>Non-conference games can air on ESPNU.</li><li>At least six games in primetime on ABC or ESPN.</li></ul><u>FOX Sports Rights Notes</u><ul><li>24-27 total games to air on FOX &amp; FS1.</li><li>Up to nine games per season will air in primetime</li><li>FOX will air the conference championship game every season.</li><li>FOX Sports will have the first choice of the weeks they want the top choice of games.</li></ul><p>Every Big Ten school must make two appearances on BTN.  At least one of those appearances must be from a conference game.</p><p>The rights deals with ESPN and FOX Sports end after the 2022-23 athletic year.  BTN\'s rights deal expires after the 2031-32 athletic year.</p><p>Source: <a href="http://mattsarzsports.blogspot.com/2017/07/a-few-content-parameters-for-big-ten.html" target="_blank">MattSarzSports Blog</a></p>'
  },
  {
    id: 'b12',
    data: '<p>The Big 12 has a pair of contracts with ESPN and FOX Sports Media Group. Both contracts expire after the 2024-25 athletic year.</p><p>The ESPN deal allows for 23 games per year starting in 2016. Games can air on ABC, ESPN, ESPN2, ESPNU and Longhorn Network (see note below re: LHN). FOX\'s deal is for up to 40 games per year to place games on FOX, FS1, FSN and FOX College Sports. A minimum of six of FSMG\'s games must appear on FOX with another six on FS1. Overall, a minimum of 25 games must air on ABC, ESPN, FOX and FS1.  Starting in 2017, the conference will reactivate their championship game.  FOX Sports will carry the game in odd numbered years and ESPN has the rights for even numbered years.</p><p>In even numbered years, FOX will retain the top choice of Big 12 games each week and in odd numbered years, ESPN will retain the top choice each week.</p><p>Individual institutions will retain the rights to at least one game not aired by ABC or FSMG, allowing those institutions to explore other avenues to televising those games. Institutions can elect to return their institutional game to FOX for their package to televise.</p><p>Regarding Longhorn Network, one Texas game per year airing on the network counts as an institutional game, like all other Big 12 schools. Any subsequent Texas games airing on Longhorn Network will count towards the ESPN contract.</p><p>Source: <a href="http://www.big12sports.com/ViewArticle.dbml?ATCLID=205680799" target="_blank">Big 12</a>'
  },
  {
    id: 'cusa',
    data: '<p>Conference USA has agreements with beIN Sports, CBS Sports Network, ESPN and Stadium for the 2018-19 athletic year.</p><p>Here are the parameters for each media partner:<ul><li>beIN Sports: Ten televised games. This agreement expires after the 2018-19 athletic year.</li><li>CBS Sports Network: Nine televised games and the conference championship game.  An additional three games produced by CBS will be available to be sublicensed exclusively to Facebook.  CBS Sports Network is considered to be the primary TV partner and this agreement is a five year agreement starting with the 2018-19 athletic year.</li><li>Stadium: 15 total games, with eight games through their linear TV feed and seven games on Facebook.</li><li>ESPN: All games not selected to air on beIN Sports, CBSSN and Stadium will air on ESPN digital platforms ESPN3 and ESPN+.</ul><p>Source: <a href="http://conferenceusa.com/news/2018/3/14/Multimedia_Rights_Annoucement_2018.aspx" target="_blank">Conference USA (TV)</a>, <a href="http://conferenceusa.com/news/2018/6/7/general-c-usa-inks-expansive-espn-deal.aspx">Conference USA (ESPN)</a></p>'
  },
  {
    id: 'mac',
    data: '<p>The MAC has a national cable contract with ESPN Networks.  The contract runs through the 2026-27 athletic year.  ESPN\'s contract includes the ability to sublicense games and guaranteed coverage for all MAC games.</p><p>The previous contract allowed for at least six regular season games will air on ESPN or ESPN2, plus a minimum of five games on ESPNU.  ESPN3 and ESPN+ will be used for any game not distributed on some form of national or regional television.  ESPN is working with the schools to self-produce ESPN3 content, providing them with production equipment.</p><p>CBS Sports Network will sublicense MAC content from ESPN.  CBSSN will sublicense twelve football games and this agreement ends after the 2018-19 athletic year.</P><p>Source: <a href="http://www.niuhuskies.com/news/2009/1/28/MAC_AND_ESPN_ANNOUNCE_RIGHTS_AGREEMENT_THROUGH_2016_17.aspx" target="_blank">Northern Illinois</a>, <a href="http://mac-sports.com/news/2014/8/19/GEN_0819145904.aspx" target="_blank">MAC (contract extension)</a>, <a href="http://mac-sports.com/news/2015/6/2/FB_0602151727.aspx" target="_blank">MAC (CBSSN sublicense)</a></p>'
  },
  {
    id: 'mw',
    data: '<p>The Mountain West has a pair of national cable contracts with CBS Sports Network and ESPN.</p><p>CBS is considered to be the "primary" TV partner.  CBS will be able to choose the top eight football games each year, then alternate with ESPN for the rest of their picks. This package is for up to 22 games. CBS\'s contract runs through the 2019-20 athletic year.</p><p>ESPN\'s package also runs through the 2019-20 athletic year and includes the rights to Boise St. home games. At least three Boise St. football games will air on ABC, ESPN, ESPN2.  ESPN can choose the platform of its choice for all other Boise St. home games.  No more than three Boise St. home games can be moved to a weeknight. ESPN will have up to 22 football games including the Boise St. home games. ESPN does have the ability to trade one Boise St. home game per year to CBS in exchange for a Boise St. road games at a Mountain West opponent.</p><p>The contract for the conference&#39;s championship game is with ESPN and runs through the 2019 game.  The game will air on ESPN or ESPN2.</p><p>The official regional television partner is AT&T Sports Rocky Mountain, formerly ROOT Sports Rocky Mountain, who will produce around 10 football games annually.  Stadium also works with the conference to produce games that will be streamed through the Moutain West Digital Network and Facebook.</p><p>ESPN and CBS select up to two more games each once AT&T Sports and Stadium select games for their packages, meaning ESPN and CBS could show up to 24 games.</p><p>Hawai\'i does not receive money from the MW TV contract unless all other Mountain West schools receive $2.3 million from the conference TV contracts.  Instead, they receive revenue from a contract with Spectrum Cable, formerly Oceanic Cable in Hawai\'i.  The contract requires at least seven games per year to be provided to the cable provider and ends after the 2019-20 athletic year.</p><p>Source: <a href="http://www.cbssports.com/collegefootball/writer/dennis-dodd/21436698/mountain-west-restructures-deal-with-cbs" target="_blank">CBS</a>, <a href="https://espnpressroom.com/us/press-releases/2013/03/espn-and-mountain-west-conference-announce-multiyear-rights-agreement/" target="_blank">ESPN</a>, <a href="http://www.themw.com/news/2015/5/15/55560e68e4b0dedffe09b97c_131372595030222862.aspx?path=fball" target="_blank">MWC for football championship</a>, <a href="https://broncosports.com/news/2013/3/26/Boise_State_and_Mountain_West_Announce_TV_Deal_with_ESPN.aspx" target="_blank">Boise St.</a>, <a href="https://broncosports.com/news/2013/5/15/Mountain_West_ROOT_SPORTS_Announce_Partnership.aspx" target="_blank">Boise St. for AT&T Sports</a>, <a href="http://www.hawaiinewsnow.com/story/24961188/senator-wants-probe-into-whether-uh-sports-tv-contractor-got-preferential-treatment" target="_blank">Hawai\'i (Spectrum/Oceanic Cable)</a></p>'
  },
  {
    id: 'p12',
    data: '<p>The Pac-12 has a pair of rightsholders: ESPN and FOX Sports Media Group. Contracts with both entities start with the 2012-13 athletic year and end after the 2023-24 athletic year.</p><u>ESPN Rights Notes</u><ul><li>At least two games on ABC, with one game required to air in primetime on the east coast</li><li>Up to twenty games on ESPN Networks (ESPN, ESPN2 &amp; ESPNU)</li><li>Of the twenty games on ESPN Networks, up to four games on Thursday nights &amp; up to four games on Friday night.</li><li>Up to four of the twenty games can air on ESPNU</li><li>Most ESPN/ESPN2 Saturday games will air at 10pm or 10:30pm ET</li></ul><u>FSMG Rights Notes</u><ul><li>A minimum of eight games on FOX</li><li>A maximum of fourteen games on FS1</li><li>At least four games on FOX will air in primetime.</li></ul><p>Overall, the conference works with both ESPN and FOX to place at least four games on Thursdays and another four games on Fridays, including the day after Thanksgiving.  FOX and ESPN will alternate airing the Pac-12 Championship Game.  In even-numbered seasons, FOX will air the game.  ESPN has the rights in odd-numbered years.</p><p>The conference has also created the Pac-12 Networks, a mix of six regional networks and a national networks, to air all other games.</p><p>A school may not appear more than nine times combined in the ESPN and FOX packages.  This is to allow the Pac-12 Networks to air at least one game from every school, assuming a school plays at least one home non-conference game.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2011/05/espn-and-pac-12-reach-wide-ranging-12-year-agreement/" target="_target">ESPN PressRoom, <a href="https://www.facebook.com/notes/fox-sports/fox-sports-media-group-secures-pac-12-multi-platform-media-rights/10150232924355700" target="_target">Facebook for FOX</a></p>'
  },
  {
    id: 'sec',
    data: '<p>The SEC has a network TV contract with CBS, a national cable deal with ESPN Networks and a new conference branded network called the SEC Network, which is completely owned by ESPN.</p><p>CBS has the rights to 12-15 regular season games and the conference championship. Up to two of those games can be non-conference games. CBS will always have the top choice of SEC games on a weekly basis.  When CBS does a doubleheader that includes a primetime game, CBS can choose the top two games on a given weekend.  When they do a doubleheader that includes a 12pm game, it must allow ESPN to reservetwo games before selecting their next game.  Also, a school may not appear on CBS more than five times during the season, with some exceptions allowing for a sixth appearance.  The SEC Championship Game is never part of the appearance count.</p><p>ESPN Networks has the rights to remaining SEC home games, primarily prime time telecasts.  A content board will be established to determine which games will air on ESPN and the SEC Network.  The plan is to air a tripleheader of games every week.  There will overflow or alternate feeds of the network to allow for multiple games to air in a single telecast window.</p><p>For 2018, CBS has sublicensed two games from ESPN, those games being West Virginia vs. Tennesee on 9/1 and Georgia at South Carolina on 9/8.  Per SEC media contact Chuck Dunlap, these two games do not count towards any CBS appearance counts.</p><p>Source: <a href="http://floridagators.com/news/2008/9/8/14419.aspx" target="_blank">Florida</a>, <a href="https://www.cbssports.com/college-football/news/sec-cbs-rework-long-term-contract/" target="_blank">CBS Sports</a>, <a href="https://espnpressroom.com/us/press-releases/2013/05/the-southeastern-conference-and-espn-announce-new-tv-network-and-digital-platform/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'sbc',
    data: '<p>The Sun Belt has an eight year contract with ESPN, starting with the 2012-13 athletic year and ending with the 2019-20 athletic year. A minimum of two football games will air on ESPN or ESPN2. ESPNU will air a minimum of five games on Thursdays or Fridays. ESPN Regional Television can also select up to five games. ESPN digital platforms such as ESPN3 and ESPN+ can also select games throughout the season.</p><p>A further eight year extension has been agreed upon with ESPN, with enhancements to the current contract including the addition of a football championship game in 2018.</p><p>Source: <a href="http://web.archive.org/web/20150910095005/https://espnmediazone.com/us/weekly-updates/midweek_20110908/#L" target="_blank">ESPN PressRoom via Archive</a>, <a href="http://sunbeltsports.org/news/2018/3/1/general-sun-belt-secures-longterm-multimedia-contract-with-espn.aspx">ESPN (extension), <a href="http://www.sunbeltsports.org/news/2014/7/16/BB_0716144040.aspx" target="_blank">Sun Belt on ESPN3</a></p>'
  },
  {
    id: 'Army',
    data: '<p>Army has a contract for home game telecasts with CBS Sports Network, with the exception of the Army-Navy game which is handled separately. A contract extension has been reached between Army and CBSSN, with the existing five year agreement to end after the 2019 season extended to after the 2022 season.</p><p>Source: <a href="http://www.goarmywestpoint.com/news/2015/1/15/CBS_Sports_Network_Signs_Multi_Year_Deal_To_Continue_As_Home_of_Army_Football.aspx?path=football" target="_blank">Army (CBS)</a>, <a href="http://goarmywestpoint.com/news/2017/9/6/athletics-army-signs-extension-with-cbs-sports-network.aspx" target="_blank">Army (CBS extension)</a>, <a href="https://cbspressexpress.com/cbs-sports/releases/view?id=47797" target="_blank">Army-Navy</a></p>'
  },
  {
    id: 'BYU',
    data: '<p>BYU has an deal with ABC/ESPN, ending after the completion of the 2019 season after an single option year was picked up to extend the contract past the 2018 season.  At least three home games will air on ABC, ESPN or ESPN2.  A minimum of one game will air on ESPNU and BYUtv, the broadcasting arm of BYU, must air at least one game per season.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/09/espn-and-byu-reach-agreement-for-football-rights-beginning-in-2011/" target="_blank">ESPN PressRoom</a>, <a href="https://espnpressroom.com/us/press-releases/2017/06/espn-televise-byu-football-2019-season/">ESPN PressRoom (2019 option exercised)</a></p>'
  },
  {
    id: 'Notre Dame',
    data: '<p>Rights to Notre Dame home games, including neutral site "home" games, are held by NBC.  The contract requires for seven "home" games per year, including neutral site games.  A new, extended contract allows for games to air on cable stations owned by NBC, such as NBC Sports Network.  The extended contract expires after the 2025 season.</p><p>Source: <a href="http://news.nd.edu/news/9528-notre-dame-nbc-extend-football-contract-through-2015/" target="_blank">Notre Dame</a></p>'
  },
  {
    id: 'UMass',
    data: '<p>All Massachusetts home games will be shown on Eleven Sports Network in 2017, with all games simulcast on NESN.</p>'
  },
  {
    id: 'Liberty',
    data: '<p>Liberty has an agreement with ESPN, allowing Liberty home football games to be available to air on ESPN\'s television & digital platforms using the Flames Sports Network production team.</p><p>Source: <a href="http://www.liberty.edu/flames/index.cfm?PID=36963&newsID=20595&teamID=9">Liberty</a></p>'
  },
  {
    id: 'NMSt',
    data: "<p>New Mexico St.'s rights are managed by Learfield Sports, who has worked to sell the television rights to their home games to local, regional and national entities.  Games produced by AggieVision will air nationally on Eleven Sports in addition to regional & local TV stations.</p>"
  }
];
