export const conferenceData = [
  {
    id: 'acc',
    data: '<p>The ACC has a contract with ESPN for all of its football television rights with games airing on ABC, ESPN, ESPN2, ESPNU, ACC Network and ACC Network Extra. This contract begins with the 2011-12 athletic year and ends with the 2036-37 athletic year.</p><p>It does not appear that there are any limits/minimums in terms of number of games over a season for the ACC with their national TV contracts. The ACC is guaranteed a game on Labor Day by ESPN.</p><p>A package of 17 games will be distributed to regional sports networks.  This package is being managed by Raycom Sports.</p><p>To cover the additions of Syracuse and Pittsburgh to the conference, the ACC signed an extension with ESPN for more money per school, adding years to the deal that started with the 2011-12 athletic year. Items relevant to football include that the ACC will have up to three Friday night football games per season, one of those three to be played on Black Friday in the afternoon or evening. Specifically, Boston College and Syracuse will each host one Friday night game per year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/07/espn-and-acc-reach-exclusive-12-year-agreement/" target="_blank">ESPN PressRoom (2010)</a>, <a href="https://espnpressroom.com/us/press-releases/2012/05/espn-and-acc-extend-exclusive-multi-platform-agreement-through-2026-27/" target="_blank">ESPN PressRoom (2012)</a>, <a href="https://espnpressroom.com/us/press-releases/2016/07/acc-network-set-launch-2019/">ESPN PressRoom (2016)</a></p>'
  },
  {
    id: 'aac',
    data: '<p>The American Athletic Conference has a contract with ESPN Networks for all of their football television rights.  ESPN will guarantee the conference a minimum of 40 games to air on ABC, ESPN, ESPN2 and ESPNU with a minimum of 20 games on ABC, ESPN and ESPN2.  ESPN+ will also carry games.</p><p>Starting in 2020, Navy home games will be divided up between ESPN\'s rights agreement and a separate agreement with CBS Sports.  ESPN will retain the right to one Navy home game per year plus the game vs. Notre Dame when Navy is considered the host team.  CBS Sports will retain all other Navy home games and retain the ability to carry the home game vs. Air Force.  Most Navy home games retained by CBS Sports will air on CBS Sports Network.</p><p>The contract with ESPN ends after the 2031-2032 athletic year while the agreement for Navy home games with CBS Sports ends after the 2027 season.</p><p>Source: <a href="http://www.theamerican.org/news/2018/5/9/football-cbs-sports-american-athletic-conference-and-navy-extend-partnership-through-2027-season.aspx" target="_blank">American & Navy</a>, <a href="http://www.theamerican.org/news/2019/3/27/general-american-athletic-conference-and-espn-agree-to-12-year-media-rights-extension.aspx" target="_blank">American</a></p>'
  },
  {
    id: 'b1g',
    data: '<p>The Big Ten has primary television contracts with ESPN and FOX Sports and a secondary TV contract with the Big Ten Network (BTN), a FOX Sports Media Group &amp; Big Ten joint venture.</p><u>ESPN Rights Notes</u><ul><li>27 total games.</li><li>All intraconference games must air on ABC, ESPN or ESPN2.</li><li>Non-conference games can air on ESPNU.</li><li>At least six games in primetime on ABC or ESPN.</li></ul><u>FOX Sports Rights Notes</u><ul><li>24-27 total games to air on FOX &amp; FS1.</li><li>Up to nine games per season will air in primetime</li><li>FOX will air the conference championship game every season.</li><li>FOX Sports will have the first choice of the weeks they want the top choice of games.</li></ul><p>Every Big Ten school must make two appearances on BTN.  At least one of those appearances must be from a conference game.</p><p>The rights deals with ESPN and FOX Sports end after the 2022-23 athletic year.  BTN\'s rights deal expires after the 2031-32 athletic year.</p><p>Source: <a href="http://mattsarzsports.blogspot.com/2017/07/a-few-content-parameters-for-big-ten.html" target="_blank">MattSarzSports Blog</a></p>'
  },
  {
    id: 'b12',
    data: '<p>The Big 12 have a pair of contracts with ESPN and FOX Sports. Both contracts expire after the 2024-25 athletic year.</p><p>The ESPN deal allows for 23 games per year and games can air on ABC, ESPN, ESPN2, ESPNU, ESPN+ and Longhorn Network (see note below re: LHN). FOX\'s deal is for up to 40 games per year to place games on FOX broadcast network and various FOX Sports pay TV platforms. A minimum of six of FSMG\'s games must appear on FOX with another six on FS1. Overall, a minimum of 25 games must air on ABC, ESPN, FOX and FS1.  Starting in 2017, the conference reactivated their championship game.  ESPN has the rights to the conference championship game to air on ABC or ESPN.</p><p>Big 12 selection order for each week will be determined via a draft of weeks before the season. In even numbered years, FOX will retain the top choice of weeks and in odd numbered years, ESPN wiil have it.</p><p>Individual institutions retain the rights to at least one game not aired by ESPN or FOX Sports, allowing those institutions to explore other avenues to televising those games. All schools except for Texas and Oklahoma will air their institutionally held games on ESPN+.  Oklahoma\'s member retained game will remain with FOX Sports through 2022.</p><p>Regarding Longhorn Network, one Texas game per year airing on the network counts as an institutional game, like all other Big 12 schools. Any subsequent Texas games airing on Longhorn Network will count towards the ESPN contract.</p><p>Source: <a href="https://big12sports.com/news/2012/9/7/205680799.aspx" target="_blank">Big 12</a>, <a href="https://espnpressroom.com/us/press-releases/2019/04/espn-big-12-conference-enhance-comprehensive-rights-agreement/" target="_blank">ESPN (championship game and member retained content)</a></p>'
  },
  {
    id: 'cusa',
    data: '<p>Conference USA has agreements with CBS Sports Network, ESPN and Stadium.</p><p>Here are the parameters for each media partner:<ul><li>CBS Sports Network: At least 14 regular season games and the conference championship game.  An additional three games produced by CBS will be available to be sublicensed exclusively to Facebook.  CBS Sports Network is considered to be the primary TV partner and this agreement is a five year agreement starting with the 2018-19 athletic year.</li><li>Stadium: 15 total games either airing on the Stadium over-the-air affiliates or through regional sports networks.</li><li>ESPN: All games not selected to air on CBSSN and Stadium will air on primarily on ESPN digital platforms ESPN3 and ESPN+. Games can be chosen to air on ESPN linear TV platforms but there is no requirement to do so.</li></ul></p><p>Source: <a href="http://conferenceusa.com/news/2018/3/14/Multimedia_Rights_Annoucement_2018.aspx" target="_blank">Conference USA (TV)</a>, <a href="http://conferenceusa.com/news/2018/6/7/general-c-usa-inks-expansive-espn-deal.aspx" target="_blank">Conference USA (ESPN)</a></p>'
  },
  {
    id: 'mac',
    data: '<p>The MAC has a national cable contract with ESPN Networks.  The contract runs through the 2026-27 athletic year.  ESPN\'s contract includes the ability to sublicense games and guaranteed coverage for all MAC games.</p><p>The previous contract allowed for at least six regular season games will air on ESPN or ESPN2, plus a minimum of five games on ESPNU.  ESPN3 and ESPN+ will be used for any game not distributed on some form of national or regional television.  ESPN is working with the schools to self-produce ESPN3 content, providing them with production equipment.</p><p>An agreement to sublicense games to CBS Sports Network from ESPN has been extended through the 2022-23 athletic year after the original agreement expired after the 2018-19 athletic year.</p><p>Source: <a href="http://www.niuhuskies.com/news/2009/1/28/MAC_AND_ESPN_ANNOUNCE_RIGHTS_AGREEMENT_THROUGH_2016_17.aspx" target="_blank">Northern Illinois</a>, <a href="http://mac-sports.com/news/2014/8/19/GEN_0819145904.aspx" target="_blank">MAC (contract extension)</a>, <a href="https://getsomemaction.com/news/2019/7/22/football-mac-cbs-sports-network-announce-four-year-contract-extension.aspx" target="_blank">MAC (CBSSN sublicense extension)</a></p>'
  },
  {
    id: 'mw',
    data: '<p>The Mountain West has a pair of national TV contracts with CBS Sports and FOX Sports.  Each partner retains the right to air up to 23 games in their primary packages.</p><p>CBS Sports is considered to be the "primary" TV partner.  They will be able to choose the top seven football games each year, then alternate with FOX Sports for the rest of their picks.  CBS Sports must air at least three games on their broadcast network and has retained the right to air an additional ten games after each partner selects their 23 games.  The extra ten games can air on CBS, CBS Sports Network or the Paramount+ streaming service.  Up to five games can air on Friday nights, which does not include games airing on special dates like Labor Day, the Friday after Thanksgiving, etc. CBS Sports also has rights to Boise State\'s four MW road games.</p><p>FOX Sports\'s package includes the rights to Boise State home games and the conference\'s football championship game.  The conference championship can air on Friday or Saturday on either FOX or FS1.  Games can air on FOX, FS1 or FS2.  Similar to CBS Sports, up to five games can air on Friday nights, excluding special dates.  FOX Sports\' package has a range of 16-23 games that can be chosen.</p><p>Stadium also has the ability to carry football games not chosen by either FOX Sports or CBS Sports to air on their television affiliates and through the Mountain West Network. Also, Hawai\'i has a separate contract through Spectrum Cable to air their most of their Mountain West games via pay-per-view on the islands after both national partners choose up to four Hawai\'i games. These games are usually streamed to the mainland with no restrictions.</p><p>Both the FOX Sports and CBS Sports agreements end after the 2025-26 athletic year.</p><p>Source: <a href="https://themw.com/documents/2020/1/9//MW_Media_Rights_Agreements_Fact_Sheet.pdf" target="_blank">MWC</a></p>'
  },
  {
    id: 'p12',
    data: '<p>The Pac-12 has a pair of rightsholders: ESPN and FOX Sports Media Group. Contracts with both entities start with the 2012-13 athletic year and end after the 2023-24 athletic year.</p><u>ESPN Rights Notes</u><ul><li>At least two games on ABC, with one game required to air in primetime on the east coast</li><li>Up to twenty games on ESPN Networks (ESPN, ESPN2 &amp; ESPNU)</li><li>Of the twenty games on ESPN Networks, up to four games on Thursday nights &amp; up to four games on Friday night.</li><li>Up to four of the twenty games can air on ESPNU</li><li>Most ESPN/ESPN2 Saturday games will air at 10pm or 10:30pm ET</li></ul><u>FSMG Rights Notes</u><ul><li>A minimum of eight games on FOX</li><li>A maximum of fourteen games on FS1</li><li>At least four games on FOX will air in primetime.</li></ul><p>Overall, the conference works with both ESPN and FOX to place at least four games on Thursdays and another four games on Fridays, including the day after Thanksgiving.  FOX and ESPN will alternate airing the Pac-12 Championship Game.  In even-numbered seasons, FOX will air the game.  ESPN has the rights in odd-numbered years.</p><p>The conference has also created the Pac-12 Networks, a mix of six regional networks and a national networks, to air all other games.</p><p>A school may not appear more than nine times combined in the ESPN and FOX packages.  This is to allow the Pac-12 Networks to air at least one game from every school, assuming a school plays at least one home non-conference game.</p>      <p>Starting with the 2021 season, each school could have one non-conference game chosen to air on ESPN+.  This is part of an updated agreement with the conference that will eventually see all SEC controlled football games move over to ESPN platforms.  In 2021, these games will also be streamed through the SEC+ online portal.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2011/05/espn-and-pac-12-reach-wide-ranging-12-year-agreement/" target="_target">ESPN PressRoom, <a href="https://www.facebook.com/notes/fox-sports/fox-sports-media-group-secures-pac-12-multi-platform-media-rights/10150232924355700" target="_target">Facebook for FOX</a></p>'
  },
  {
    id: 'sec',
    data: '<p>The SEC has a network TV contract with CBS, a national cable deal with ESPN Networks and a new conference branded network called the SEC Network, which is completely owned by ESPN.</p><p>CBS has the rights to 12-15 regular season games and the conference championship. Up to two of those games can be non-conference games. CBS will always have the top choice of SEC games on a weekly basis.  When CBS does a doubleheader that includes a primetime game, CBS can choose the top two games on a given weekend.  When they do a doubleheader that includes a 12pm game, it must allow ESPN to reservetwo games before selecting their next game.  Also, a school may not appear on CBS more than five times during the season, with some exceptions allowing for a sixth appearance.  The SEC Championship Game is never part of the appearance count.</p><p>ESPN Networks has the rights to remaining SEC home games, primarily prime time telecasts.  A content board will be established to determine which games will air on ESPN and the SEC Network.  The plan is to air a tripleheader of games every week.  There will overflow or alternate feeds of the network to allow for multiple games to air in a single telecast window.</p><p>Source: <a href="http://floridagators.com/news/2008/9/8/14419.aspx" target="_blank">Florida</a>, <a href="https://www.cbssports.com/college-football/news/sec-cbs-rework-long-term-contract/" target="_blank">CBS Sports</a>, <a href="https://espnpressroom.com/us/press-releases/2013/05/the-southeastern-conference-and-espn-announce-new-tv-network-and-digital-platform/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'sbc',
    data: '<p>The Sun Belt has an agreement with ESPN, starting with the 2020-21 athletic year and ending with the 2030-31 athletic year through an additional three year extension. With the new extension, a minimum of 15 football games, up from a minimum of ten games, will air on ABC, ESPN, ESPN2 and ESPNU with the conference\'s football championship game on ABC, ESPN or ESPN2 on a Saturday. Through the regular season, the contract extension will allow more games to be televised on Saturdays. ESPN digital platforms such as ESPN3 and ESPN+ can also select games throughout the season.</p><p>Source: <a href="http://sunbeltsports.org/news/2018/3/1/general-sun-belt-secures-longterm-multimedia-contract-with-espn.aspx" target="_blank">Sun Belt</a>, <a href="https://sunbeltsports.org/news/2021/7/22/general-sun-belt-espn-expand-media-rights-partnership.aspx">Sun Belt (ESPN extension)</a></p>'
  },
  {
    id: 'Army',
    data: '<p>Army has a contract for home game telecasts with CBS Sports, airing the majority of games on CBS Sports Network, with the exception of the Army-Navy game which is handled separately. The existing agreement is scheduled to end after the 2022 season but has been extended through the 2028 season.</p><p>Source: <a href="http://www.goarmywestpoint.com/news/2015/1/15/CBS_Sports_Network_Signs_Multi_Year_Deal_To_Continue_As_Home_of_Army_Football.aspx?path=football" target="_blank">Army (CBS)</a>, <a href="https://goarmywestpoint.com/news/2021/6/16/football-cbs-sports-and-army-extend-partnership-through-2028.aspx" target="_blank">Army (CBS extension)</a>, <a href="https://cbspressexpress.com/cbs-sports/releases/view?id=47797" target="_blank">Army-Navy</a></p>'
  },
  {
    id: 'BYU',
    data: '<p>BYU has an agreement with ESPN, ending after the completion of the 2026 season.  ESPN retains rights to at least four BYU home and neutral site games where BYU is designated as the home team, with at least three airing on ABC, ESPN or ESPN2.  ESPNU can also carry BYU games but is not required to carry any.  BYUtv, the broadcasting arm of BYU, must air at least one game per season.  All games airing on BYUtv will also be carried through the ESPN app.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2020/01/espn-and-byu-reach-new-media-rights-agreement-for-cougars-home-football-games/" target="_blank">ESPN PressRoom</a></p>'
  },
  {
    id: 'Notre Dame',
    data: '<p>Rights to Notre Dame home games, including neutral site "home" games, are held by NBC.  The contract requires for seven "home" games per year, including neutral site games.  A new, extended contract allows for games to air on cable stations and other platforms owned by NBC, such as USA Network and Peacock.  The extended contract expires after the 2025 season.</p><p>Source: <a href="http://news.nd.edu/news/9528-notre-dame-nbc-extend-football-contract-through-2015/" target="_blank">Notre Dame</a></p>'
  },
  {
    id: 'UMass',
    data: '<p>UMass has entered into a two year agreement with FloSports to carry their football games nationally, in addition to regional TV coverage through NESN.</p><p>Source: <a href="https://umassathletics.com/news/2019/8/5/umass-announces-football-broadcast-partnership-with-flosports-nesn-home-game-kickoff-times.aspx" target="_blank">UMass</a></p>'
  },
  {
    id: 'Liberty',
    data: '<p>Liberty has an agreement with ESPN, allowing Liberty home football games to be available to air on ESPN\'s television & digital platforms using the Flames Sports Network production team. A new five year agreement starts in 2021 with at least one home game per season to air on ESPN linear TV platforms and a second game to be chosen if it is scheduled for a non-traditional day of the week (ie. not Saturday).</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2021/07/liberty-extends-multi-year-agreement-with-espn-for-football-media-rights/" target="_blank">Liberty</a></p>'
  },
  {
    id: 'NMSt',
    data: '<p>NM State\'s rights are managed by Learfield Sports, who has worked to sell the television rights to their home games to local, regional and national entities.  Learfield has sold OTT rights to FloSports for a three year period, ending after the 2022 season.</p><p>Source: <a href="https://www.flosports.tv/flosports-to-broadcast-new-mexico-state-university-football/" target="_blank">FloSports</a></p>'
  },
  {
    id: 'UConn',
    data: '<p>UConn has a rights agreement with CBS Sports Network running through the 2023 season.  From 2021-2023, all home games will be televised by CBSSN.</p><p>Source: <a href="https://uconnhuskies.com/news/2020/5/11/uconn-and-cbs-sports-agree-to-multi-year-television-deal-for-home-football-games.aspx" target="_blank">UConn</a></p>'
  }
];
