export const conferenceData = [
  {
    id: 'acc',
    data: '<p>The ACC has a contract with ESPN for all of its football television rights with games airing on ABC, ESPN, ESPN2, ESPNU, ACC Network and ACC Network Extra/ESPN+. This contract begins with the 2011-12 athletic year and ends with the 2036-37 (maybe? maybe just 2026-27?) athletic year.</p><p>It does not appear that there are any limits/minimums in terms of number of games over a season for the ACC with their national TV contracts. The ACC is guaranteed a game on Labor Day by ESPN.</p><p>A package of 13 games will be distributed to The CW.  This package is being managed by Raycom Sports as part of a sublicense to Raycom from ESPN.  Previously, Raycom managed a 17 game football package that was shown on regional sports networks.  This 13 game package is replacing the RSN package.  It will run through the 2026-27 athletic year.</p><p>To cover the additions of Syracuse and Pittsburgh to the conference, the ACC signed an extension with ESPN for more money per school, adding years to the deal that started with the 2011-12 athletic year. Items relevant to football include that the ACC will have up to three Friday night football games per season, one of those three to be played on Black Friday in the afternoon or evening. Specifically, Boston College and Syracuse will each host one Friday night game per year.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2010/07/espn-and-acc-reach-exclusive-12-year-agreement/" target="_blank">ESPN PressRoom (2010)</a>, <a href="https://espnpressroom.com/us/press-releases/2012/05/espn-and-acc-extend-exclusive-multi-platform-agreement-through-2026-27/" target="_blank">ESPN PressRoom (2012)</a>, <a href="https://espnpressroom.com/us/press-releases/2016/07/acc-network-set-launch-2019/">ESPN PressRoom (2016)</a></p>'
  },
  {
    id: 'aac',
    data: '<p>The American Athletic Conference has a contract with ESPN Networks for all of their football television rights.  ESPN will guarantee the conference a minimum of 40 games to air on ABC, ESPN, ESPN2 and ESPNU with a minimum of 20 games on ABC, ESPN and ESPN2.  ESPN+ will also carry games.</p>      <p>Navy home games will be divided up between ESPN\'s rights agreement and a separate agreement with CBS Sports.  ESPN will retain the right to one Navy home game per year plus the game vs. Notre Dame when Navy is considered the host team.  CBS Sports will retain all other Navy home games and retain the ability to carry the home game vs. Air Force.  Most Navy home games retained by CBS Sports will air on CBS Sports Network.</p><p>Army home games will remain with CBS Sports Network through the end of the previously signed agreement with CBS which ends after the 2028 season.</p><p>The contract with ESPN ends after the 2031-2032 athletic year while the agreement for Navy home games with CBS Sports ends after the 2027 season.</p><p>Source: <a href="http://www.theamerican.org/news/2018/5/9/football-cbs-sports-american-athletic-conference-and-navy-extend-partnership-through-2027-season.aspx" target="_blank">American & Navy</a>, <a href="http://www.theamerican.org/news/2019/3/27/general-american-athletic-conference-and-espn-agree-to-12-year-media-rights-extension.aspx" target="_blank">American</a></p>'
  },
  {
    id: 'b1g',
    data: '<p>The Big Ten has primary television contracts with FOX Sports, CBS Sports, NBC Sports and a secondary TV contract with the Big Ten Network (BTN), a FOX Sports Media Group &amp; Big Ten joint venture. The agreements with FOX Sports, CBS Sports and NBC Sports are each for seven years and will expire at the end of the 2029-30 athletic year.</p><u>FOX Sports Rights Notes</u><ul><li>At least 32 total games to air on FOX &amp; FS1 in 2024.</li><li>Most games on FOX broadcast network will air at 12pm Eastern time.</li><li>FOX Sports will have the first choice of the weeks they want the top choice of games over the course of the season.</li><li>Big Ten Championship games, all in odd numbered season (2025, 2027 and 2029)</li></ul><u>CBS Sports Rights Notes</u><ul><li>7 games to air on CBS in 2023. Starting in 2024, the number will increase with up to 15 games starting in 2024.</li><li>At the moment, it is unknown when most games be scheduled in 2023.  In 2024 and future seasons, games will usually air at 3:30pm Eastern.</li><li>CBS will carry one Black Friday game per season during the afternoon.</li><li>Two Big Ten Championship games: 2024 and 2028.</li></ul><u>NBC Sports Rights Notes</u><ul><li>15 games to air on NBC per season.</li><li>In addition to the games on NBC, 8 additional games per season will air on Peacock. In 2023, NBC intended to air 16 games.  Instead of that, they will air an additional game exclusively on Peacock meaning nine games will air on Peacock for 2023 per NBC Sports president Rick Cordella.</li><li>Most NBC games will air in primetime on the east coast while games on Peacock could be scheduled for any game window or start time.</li><li>NBC will carry one Black Friday game per season in primetime.</li><li>NBC has rights to the 2026 Big Ten Championship.</li></ul><p>Every Big Ten school must make two appearances on BTN.  At least one of those appearances must be from a conference game.  Atl least 50 games will air on BTN.</p><p>Source: <a href="https://www.cbssports.com/college-football/news/big-ten-reaches-seven-year-media-rights-deal-with-cbs-fox-and-nbc-for-football-basketball-through-2029-30/" target="_blank">CBS Sports</a>, <a href="https://bigten.org/news/2022/8/18/general-big-ten-conference-announces-groundbreaking-media-rights-agreements-providing-fans-unprecedented-access-and-student-athletes-greater-exposure-than-any-other-collegiate-sports-conference-in-history.aspx" target="_blank">Big Ten</a></p>'
  },
  {
    id: 'b12',
    data: '<p>The Big 12 have a pair of contracts with ESPN and FOX Sports. Both contracts expire after the 2024-25 athletic year with a six year extension agreed to but not announced by the conference through the 2030-31 athletic year.</p><p>For 2024 football season, the ESPN deal allows for 32 games per year and games can air on ABC, ESPN, ESPN2 and ESPNU, though I assume that there will be an incremental increase for ESPN due to the increase in inventory with 16 members. FOX\'s deal is for up to 40 games per year to place games on FOX broadcast network and various FOX Sports pay TV platforms, though this may also be adjusted for the 2024 seasons. A minimum of six of FSMG\'s games must appear on FOX with another six on FS1. Overall, a minimum of 25 games must air on ABC, ESPN, FOX and FS1.  Starting in 2017, the conference reactivated their championship game.  ESPN has the rights to the conference championship game to air on ABC or ESPN.</p><p>Big 12 selection order for each week will be determined via a draft of weeks before the season. In even numbered years, FOX will retain the top choice of weeks and in odd numbered years, ESPN wiil have it.<p>Individual institutions retain the rights to at least one game not aired by ESPN or FOX Sports, allowing those institutions to explore other avenues to televising those games. All schools except for Texas will air their institutionally held games on ESPN+. Starting with the 2025 season, all institutional rights will be removed and part of the national TV packages.</p><p>Starting with the 2025 season, ESPN will be the primary rightsholder. They will have priority for choosing the top four selections for the entire season and then roughly alternate with FOX Sports through the top 20 selections.<p>Source: <a href="https://big12sports.com/news/2012/9/7/205680799.aspx" target="_blank">Big 12</a>, <a href="https://espnpressroom.com/us/press-releases/2019/04/espn-big-12-conference-enhance-comprehensive-rights-agreement/" target="_blank">ESPN (championship game and member retained content)</a>, <a href="https://www.sportsbusinessjournal.com/SB-Blogs/Breaking-News/2022/10/Big-12-renews-media-deal-ESPN-Fox.aspx" target="_blank">Sports Business Journal (contract extension)</a></p>'
  },
  {
    id: 'cusa',
    data: '<p>Conference USA has five year agreements with CBS Sports Network and ESPN.</p><p>Here are the parameters for each media partner:<ul><li>CBS Sports Network: 18 regular season games and the conference championship game. They are considered the primary TV partner.</li><li>ESPN Networks: Eight games for linear TV networks (ESPN, ESPN2, ESPNU) and all games not airing on linear TV by either TV partner for ESPN+</li></ul><p>C-USA will schedule all October games to air on weeknights. This is where ESPN will select most of their football games for ESPN, ESPN2 and ESPNU. Both rights agreements expire after the 2027-28 athletic year.</p></p><p>Source: <a href="https://conferenceusa.com/news/2022/11/10/general-conference-usa-announces-multimedia-rights-deal.aspx" target="_blank">Conference USA</a></a></p>'
  },
  {
    id: 'mac',
    data: '<p>The MAC has a national cable contract with ESPN Networks.  The contract runs through the 2026-27 athletic year.  ESPN\'s contract includes the ability to sublicense games and guaranteed coverage for all MAC games.</p><p>The previous contract allowed for at least six regular season games will air on ESPN or ESPN2, plus a minimum of five games on ESPNU.  ESPN+ will be used for any game not distributed on some form of national or regional television.  ESPN is working with the schools to self-produce ESPN+ content, providing them with production equipment.</p><p>An agreement to sublicense games to CBS Sports Network from ESPN appears to have been extended past its 2022-23 athletic year expiration date.</p><p>Source: <a href="http://www.niuhuskies.com/news/2009/1/28/MAC_AND_ESPN_ANNOUNCE_RIGHTS_AGREEMENT_THROUGH_2016_17.aspx" target="_blank">Northern Illinois</a>, <a href="http://mac-sports.com/news/2014/8/19/GEN_0819145904.aspx" target="_blank">MAC (contract extension)</a>, <a href="https://getsomemaction.com/news/2019/7/22/football-mac-cbs-sports-network-announce-four-year-contract-extension.aspx" target="_blank">MAC (CBSSN sublicense extension)</a></p>'
  },
  {
    id: 'mw',
    data: '<p>The Mountain West has three national TV contracts with CBS Sports, FOX Sports and TNT Sports.</p><p>CBS Sports is considered to be the "primary" TV partner.  They will be able to choose the top seven football games each year, then alternate with FOX Sports for the rest of their picks.  CBS Sports must air at least three games on their broadcast network and has retained the right to air an additional ten games after each partner selects their 23 games.  The extra ten games can air on CBS, CBS Sports Network or the Paramount+ streaming service.  Up to five games can air on Friday nights, which does not include games airing on special dates like Labor Day, the Friday after Thanksgiving, etc. CBS Sports also has rights to Boise State\'s four MW road games.</p><p>FOX Sports\'s package includes the rights to Boise State home games and the conference\'s football championship game.  The conference championship can air on Friday or Saturday on either FOX or FS1.  Games can air on FOX, FS1 or FS2.  Similar to CBS Sports, up to five games can air on Friday nights, excluding special dates.  FOX Sports\' package has a range of 16-23 games that can be chosen.</p><p>TNT Sports has entered the picture on a multi-year agreement.  It appears that they will choose games after both CBS Sports and FOX Sports.  More information is to be announced about TNT Sports\' coverage.</p><p>Also, Hawai\'i has a separate contract through Spectrum Cable to air their most of their Mountain West games via pay-per-view on the islands after both national partners choose up to four Hawai\'i games. These games are usually streamed to the mainland with no restrictions.</p><p>Both the FOX Sports and CBS Sports agreements end after the 2025-26 athletic year.</p><p>Source: <a href="https://themw.com/documents/2020/1/9//MW_Media_Rights_Agreements_Fact_Sheet.pdf" target="_blank">MWC</a>, <a href="https://press.wbd.com/us/media-release/tnt-sports-and-mountain-west-reach-multi-year-college-football-agreement-beginning" target="_blank">TNT Sports</a></p>'
  },
  {
    id: 'p12',
    data: '<p>Pac-12 schools Oregon State and Washington State have placed most of their games on CW. Two games have been selected to air on FOX.</p><p>Source: <a href="https://pac-12.com/article/2024/05/14/pac-12-football-be-featured-nationally-across-cw-network-fox-sports-2024" target="_blank">Pac-12</a></p>'
  },
  {
    id: 'sec',
    data: '<p>The SEC has a TV contract with ESPN for all SEC-owned content. Games will appear on ABC, all ESPN linear TV platforms, SEC Network and SEC+/ESPN+.</p><p>Per ESPN, the intention is to have a "late afternoon" game regularly on ABC along with SEC games airing on ABC in primetime.  The SEC championship game will now air on ABC as well.</p><p>Starting with the 2021 season, each school could have one non-conference game chosen to air on ESPN+.  This is part of an updated agreement with the conference that will eventually see all SEC controlled football games move over to ESPN platforms.  In 2021, these games will also be streamed through the SEC+ online portal.</p><p>Source: <a href="https://espnpressroom.com/us/press-releases/2013/05/the-southeastern-conference-and-espn-announce-new-tv-network-and-digital-platform/" target="_blank">SEC Network from ESPN PressRoom</a>, <a href="https://espnpressroom.com/us/press-releases/2020/12/espn-and-southeastern-conference-reach-a-new-10-year-agreement/" target="_blank">2024 Agrement with 2021 ESPN+</a></p>'
  },
  {
    id: 'sbc',
    data: '<p>The Sun Belt has an agreement with ESPN, starting with the 2020-21 athletic year and ending with the 2030-31 athletic year through an additional three year extension. With the new extension, a minimum of 15 football games, up from a minimum of ten games, will air on ABC, ESPN, ESPN2 and ESPNU with the conference\'s football championship game on ABC, ESPN or ESPN2 on a Saturday. Through the regular season, the contract extension will allow more games to be televised on Saturdays. ESPN digital platforms such as ESPN+ can also select games throughout the season.</p><p>Source: <a href="http://sunbeltsports.org/news/2018/3/1/general-sun-belt-secures-longterm-multimedia-contract-with-espn.aspx" target="_blank">Sun Belt</a>, <a href="https://sunbeltsports.org/news/2021/7/22/general-sun-belt-espn-expand-media-rights-partnership.aspx">Sun Belt (ESPN extension)</a></p>'
  },
  {
    id: 'Notre Dame',
    data: '<p>Rights to Notre Dame home games, including neutral site "home" games, are held by NBC.  The contract requires for seven "home" games per year, including neutral site games.  A new, extended contract allows for games to air on cable stations and other platforms owned by NBC, such as USA Network and Peacock.  The extended contract expires after the 2029 season.</p><p>Source: <a href="http://news.nd.edu/news/39337-notre-dame-and-nbc-extend-football-contract-to-2025/ " target="_blank">Notre Dame (2025 extension)</a>, <a href="https://nbcsportsgrouppressbox.com/2023/11/18/notre-dame-and-nbc-sports-continue-historic-football-partnership-with-games-to-be-presented-on-nbc-and-peacock-through-the-2029-season/ " target="_blank">NBC Sports (2029 extension)</a></p>'
  },
  {
    id: 'UMass',
    data: '<p>UMass has entered into a three year agreement with ESPN to carry their football games.  Most games will air via ESPN+, but one home game per season in 2023 and 2024 will air via ESPN\'s linear TV channels.</p><p>Source: <a href="https://umassathletics.com/news/2022/8/18/massachusetts-announces-football-broadcast-agreement-with-espn-2022-home-game-kickoff-times.aspx" target="_blank">UMass</a></p>'
  },
  {
    id: 'UConn',
    data: '<p>UConn has a rights agreement with CBS Sports Network running through the 2024 season.  Most home games will be televised by the network.</p><p>Source: <a href="https://uconnhuskies.com/news/2020/5/11/uconn-and-cbs-sports-agree-to-multi-year-television-deal-for-home-football-games.aspx" target="_blank">UConn</a></p>'
  }
];
